name = "9router"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[alias]
"@/lib/usageDb.js" = "./src/stubs/usageDb.js"
"../../src/shared/utils/machineId.js" = "./src/stubs/machineId.js"
"../../src/shared/utils/clineAuth.js" = "./src/stubs/clineAuth.js"
"uuid" = "./node_modules/uuid/dist/index.js"
"undici" = "./src/stubs/undici.js"

[[kv_namespaces]]
binding = "KV"
id = "d482e820a5434670836634c23cf7245e"

[[d1_databases]]
binding = "DB"
database_name = "proxy-db"
database_id = "bfaf09bb-53ac-4e2e-9188-7d9c76a9c8e4"
